version: '3.8'

services:
  pgvector-db:
    image: ankane/pgvector:latest
    container_name: pgvector-db
    restart: unless-stopped
    ports:
    - "5433:5432"
    environment:
      POSTGRES_USER: raguser
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: rag_db
    volumes:
      - pgvector-data:/var/lib/postgresql/data

volumes:
  pgvector-data:
